# Установка базового образа     
FROM python:3.11

# Рабочая директория
WORKDIR /scan

# Монтируем файлы
COPY . /scan

# Устанавливаем зависимости
RUN pip install -r requirements.txt

EXPOSE 8081

ENTRYPOINT ["python3"]

CMD ["scanner.py"]


